# Generated by Django 5.0.1 on 2024-02-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=150)),
                ('Marca', models.CharField(max_length=30)),
                ('Ano', models.IntegerField()),
            ],
        ),
    ]
